# Denne filen lager noen datasett som er nødvendig i preprosesseringen

# resh_voksen_barn <-
#   readxl::read_xlsx("~/mydata/norspis/RESH, navn, BUV, org.nr. 18.12.23.xlsx",
#                     sheet = 1)
# resh_voksen_barn <- resh_voksen_barn[match(unique(resh_voksen_barn$RESH),
#                                            resh_voksen_barn$RESH), ] %>%
#   rename(AvdRESH = RESH,
#          Kortnavn = `Kortnavn i årsrapporten`,
#          AvdBUV = `Barn/unge (BU) eller voksen (V)`,
#          orgnr = Org.nr.) %>%
#   select(AvdRESH, Kortnavn, AvdBUV, orgnr)
#
# write.csv(resh_voksen_barn, "~/mydata/norspis/resh_voksen_barn.csv", row.names = F)

resh_voksen_barn <-
  tibble::tribble(
    ~AvdRESH, ~Kortnavn, ~AvdBUV, ~orgnr,
    106854,"NKS Jæren DPS","V",333333,
    4210626,"HSYK: Allm.pol. BU Mosjøen","BU",875326562,
    4210303,"ST. OLAVS: Spes.pol. V","V",883974832,
    4208548,"DIAKONSYK: Allm.pol. V","V",974116804,
    700698,"UNN: Reg.døgn BU","BU",974547031,
    707383,"AHUS: EFS Spes.pol. V","V",974705168,
    4207041,"AHUS: EFS Spes.døgn V","V",974705168,
    105806,"HNT: Reg. V","V",974754142,
    700821,"NLSH: Reg. V","V",974795345,
    4210562,"NLSH: Spes.pol. BU","BU",975296008,
    4210825,"HSYK: Allm.pol. V Mosjøen","V",975326551,
    4204191,"CAPIO: Spes.døgn BU","BU",980524493,
    4208300,"SIHF: Spes.døgn V","V",983971709,
    4204275,"SOHF: Spes.døgn V","V",983971768,
    4207697,"HNT: MHOBY","V",983974791,
    102152,"HSYK: Allm.pol. V Sandnessjøen","V",983974929,
    102154,"HSYK: Allm.pol. BU Sandnessjøen","BU",983974929,
    104083,"SSHF: Spes.døgn V","V",983975240,
    105008,"SSHF: Allm.pol. V Arendal/Froland","V",983975240,
    108462,"SSHF Allm.pol. V Solvang","V",983975240,
    104364,"SIV: Spis.pol. V","V",983975259,
    4209009,"SIV: Spes.pol. BU","BU",983975259,
    109979,"OUS: Reg. BU","BU",987547243,
    107026,"HB: Reg. V","V",991992677,
    110361,"OUS: Spes.pol. V","V",998158923)



# variabeloversikt <- readxl::read_xlsx("~/mydata/norspis/Variabler i forløp v2.xlsx",
#                                       sheet = 1) %>%
#   rename(status = `Start/slutt/utgått`,
#          OppfolgingNum = `Også i tabellen OppfolgingNum`) %>%
#   mutate(status = case_when(status == "Ikke slutt" ~ "IkkeSlutt",
#                             status == "Ikke start" ~ "IkkeStart",
#                             status == "Utgått" ~ "Utgaatt"))
# write.csv(variabeloversikt, "~/mydata/norspis/variabeloversikt.csv", row.names = F)

variabeloversikt <-
  tibble::tribble(
    ~Tabell, ~status, ~Variabelnavn, ~OppfolgingNum,
    "AlleScorer","IkkeStart","PasOppErfaring","Nei",
    "AlleScorer","IkkeStart","PasOppTilfredshet","Nei",
    "AlleScorer","IkkeStart","PasOppTilgjengelighet","Nei",
    "AlleScorer","IkkeStart","PasOppSikkerhet","Nei",
    "AlleScorer","Utgaatt","RAND36FysFunk","Nei",
    "AlleScorer","Utgaatt","RAND36RollebegFys","Nei",
    "AlleScorer","Utgaatt","RAND36RollebegEmo","Nei",
    "AlleScorer","Utgaatt","RAND36Tretthet","Nei",
    "AlleScorer","Utgaatt","RAND36MentalHelse","Nei",
    "AlleScorer","Utgaatt","RAND36SosialFunk","Nei",
    "AlleScorer","Utgaatt","RAND36Smerte","Nei",
    "AlleScorer","Utgaatt","RAND36GenHelse","Nei",
    "AlleScorer","Utgaatt","RAND36EndringHelse","Nei",
    "AlleScorer","Utgaatt","HoNOSSumScore","Nei",
    "AlleScorer","Utgaatt","HoNOSSnittScore","Nei",
    "AlleScorer","Utgaatt","HoNOSAntSvar","Nei",
    "AlleScorer","Utgaatt","HoNOSCATotalSum","Nei",
    "AlleScorer","Utgaatt","HoNOSCATotalSnitt","Nei",
    "AlleScorer","Utgaatt","HoNOSCADelASum","Nei",
    "AlleScorer","Utgaatt","HoNOSCADelASnitt","Nei",
    "AlleScorer","Utgaatt","HoNOSCADelBSum","Nei",
    "AlleScorer","Utgaatt","HoNOSCADelBSnitt","Nei",
    "AlleScorer","Utgaatt","HoNOSCATotalSvar","Nei",
    "AlleScorer","Utgaatt","HoNOSCADelASvar","Nei",
    "AlleScorer","Utgaatt","HoNOSCADelBSvar","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUAkse1","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUAkse2","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUAkse3","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUAkse4","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUAkse5","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUAkse6","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUDSM5utfylles","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUDSM5Hoved","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUDSM5ANSub","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUDSM5AnnenSub","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUDSM5ANAlvGrd","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUDSM5BNAlvGrd","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUDSM5OverspisAlvGrd","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUForstLukketAV","Nei",
    "EnkeltLeddNum","IkkeStart","DiagBUForstLukket","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVSF","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVSomatiske","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVMalabsorpsjon","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVDiabetes","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVDSM5utfylles","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVDSM5Hoved","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVDSM5ANSub","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVDSM5AnnenSub","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVDSM5ANAlvGrd","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVDSM5BNAlvGrd","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVDSM5OverspisAlvGrd","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVForstLukketAV","Nei",
    "EnkeltLeddNum","IkkeStart","DiagVForstLukket","Nei",
    "EnkeltLeddNum","Utgaatt","H01Atferd","Nei",
    "EnkeltLeddNum","Utgaatt","H02Selvskade","Nei",
    "EnkeltLeddNum","Utgaatt","H03Rusmisbruk","Nei",
    "EnkeltLeddNum","Utgaatt","H04KognitiveProbl","Nei",
    "EnkeltLeddNum","Utgaatt","H05FysiskeProbl","Nei",
    "EnkeltLeddNum","Utgaatt","H06Hallusinasjoner","Nei",
    "EnkeltLeddNum","Utgaatt","H07Stemningsleie","Nei",
    "EnkeltLeddNum","Utgaatt","H08AndreProbl","Nei",
    "EnkeltLeddNum","Utgaatt","H08aVelgTypeProbl","Nei",
    "EnkeltLeddNum","Utgaatt","H09ForhAndre","Nei",
    "EnkeltLeddNum","Utgaatt","H10ADLProbl","Nei",
    "EnkeltLeddNum","Utgaatt","H11BoligProbl","Nei",
    "EnkeltLeddNum","Utgaatt","H12YrkeProbl","Nei",
    "EnkeltLeddNum","Utgaatt","HForstLukketAV","Nei",
    "EnkeltLeddNum","Utgaatt","HForstLukket","Nei",
    "EnkeltLeddNum","Utgaatt","HCA01Atferd","Nei",
    "EnkeltLeddNum","Utgaatt","HCA02Aktivitetsniva","Nei",
    "EnkeltLeddNum","Utgaatt","HCA03Selvskade","Nei",
    "EnkeltLeddNum","Utgaatt","HCA04Rusmisbruk","Nei",
    "EnkeltLeddNum","Utgaatt","HCA05SkoleSprak","Nei",
    "EnkeltLeddNum","Utgaatt","HCA06FysiskProblem","Nei",
    "EnkeltLeddNum","Utgaatt","HCA07Hallusinasjoner","Nei",
    "EnkeltLeddNum","Utgaatt","HCA08SomatiskSymp","Nei",
    "EnkeltLeddNum","Utgaatt","HCA09EmosjonelleSymp","Nei",
    "EnkeltLeddNum","Utgaatt","HCA10JevnaldrProbl","Nei",
    "EnkeltLeddNum","Utgaatt","HCA11Egenomsorg","Nei",
    "EnkeltLeddNum","Utgaatt","HCA12FamilieProbl","Nei",
    "EnkeltLeddNum","Utgaatt","HCASkoleframmote","Nei",
    "EnkeltLeddNum","Utgaatt","HCADelButfylles","Nei",
    "EnkeltLeddNum","Utgaatt","HCA14ProblKunnskap","Nei",
    "EnkeltLeddNum","Utgaatt","HCA15Mangelinfo","Nei",
    "EnkeltLeddNum","Utgaatt","HCAForstLukketAV","Nei",
    "EnkeltLeddNum","Utgaatt","HCAForstLukket","Nei",
    "EnkeltLeddNum","IkkeStart","POTilfredsBesvart","Nei",
    "EnkeltLeddNum","IkkeStart","POArsakIkkeBesvart","Nei",
    "EnkeltLeddNum","IkkeStart","PO01Forstod","Nei",
    "EnkeltLeddNum","IkkeStart","PO02Tillit","Nei",
    "EnkeltLeddNum","IkkeStart","PO03InfoDiagnose","Nei",
    "EnkeltLeddNum","IkkeStart","PO04Tilpasset","Nei",
    "EnkeltLeddNum","IkkeStart","PO05Involvert","Nei",
    "EnkeltLeddNum","IkkeStart","PO06Organisert","Nei",
    "EnkeltLeddNum","IkkeStart","PO07Tilfredsstillende","Nei",
    "EnkeltLeddNum","IkkeStart","PO08Tilgjengelighet","Nei",
    "EnkeltLeddNum","IkkeStart","PO09Utbytte","Nei",
    "EnkeltLeddNum","IkkeStart","PO10Pasientsikkerhet","Nei",
    "EnkeltLeddNum","IkkeStart","POLukketViaEproms","Nei",
    "EnkeltLeddNum","IkkeStart","POForstLukketAV","Nei",
    "EnkeltLeddNum","IkkeStart","POForstLukket","Nei",
    "EnkeltLeddNum","IkkeSlutt","BTilfredsBesvart","Ja",
    "EnkeltLeddNum","IkkeSlutt","BArsakIkkeBesvart","Ja",
    "EnkeltLeddNum","IkkeSlutt","B01Sivilstatus","Nei",
    "EnkeltLeddNum","IkkeSlutt","B02EgneBarn","Nei",
    "EnkeltLeddNum","IkkeSlutt","B03Bosituasjon","Nei",
    "EnkeltLeddNum","IkkeSlutt","B03BostatusV1_4","Ja",
    "EnkeltLeddNum","IkkeSlutt","B04PabegyntUtd","Nei",
    "EnkeltLeddNum","IkkeSlutt","B05FullfortUtd","Nei",
    "EnkeltLeddNum","IkkeSlutt","B04UtdanningV1_4","Ja",
    "EnkeltLeddNum","IkkeSlutt","B06Hovedaktivitet","Nei",
    "EnkeltLeddNum","IkkeSlutt","B06ArbeidsstatusV1_4","Ja",
    "EnkeltLeddNum","IkkeSlutt","B07Hovedinntekt","Nei",
    "EnkeltLeddNum","IkkeSlutt","B08StartAldrProbl","Nei",
    "EnkeltLeddNum","IkkeSlutt","B09LavestVekt","Nei",
    "EnkeltLeddNum","IkkeSlutt","B09aAldrLavestVekt","Nei",
    "EnkeltLeddNum","IkkeSlutt","B10HoyestVekt","Nei",
    "EnkeltLeddNum","IkkeSlutt","B10aAldrHoyestVekt","Nei",
    "EnkeltLeddNum","IkkeSlutt","B11FamilieSF","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12TidlBehSF","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12aPrimarhtj","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12aSpesialisthtj","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12aSpesEnhetSF","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12aAnnenInstans","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12bTidlTvangsinnl","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12cAldrForsteBeh","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12dArTilBehstart","Nei",
    "EnkeltLeddNum","IkkeSlutt","B12dMndTilBehstart","Nei",
    "EnkeltLeddNum","IkkeSlutt","B13MensNoenGang","Nei",
    "EnkeltLeddNum","IkkeSlutt","B14MensSiste3mnd","Nei",
    "EnkeltLeddNum","IkkeSlutt","B15MedPrevensjon","Nei",
    "EnkeltLeddNum","IkkeSlutt","B16Gravid","Nei",
    "EnkeltLeddNum","IkkeSlutt","B17FysMishandl","Nei",
    "EnkeltLeddNum","IkkeSlutt","B18PsykMishandl","Nei",
    "EnkeltLeddNum","IkkeSlutt","B19Overgrep","Nei",
    "EnkeltLeddNum","IkkeSlutt","B20Mobbing","Nei",
    "EnkeltLeddNum","IkkeSlutt","B21SelvskadTidl","Nei",
    "EnkeltLeddNum","IkkeSlutt","B22SelvskadSisteAr","Nei",
    "EnkeltLeddNum","IkkeSlutt","B23SelvmordFTidl","Nei",
    "EnkeltLeddNum","IkkeSlutt","B24SelvmordFSisteAr","Nei",
    "EnkeltLeddNum","IkkeSlutt","B25Avhengighet","Nei",
    "EnkeltLeddNum","IkkeSlutt","BLukketViaEproms","Ja",
    "EnkeltLeddNum","IkkeSlutt","BForstLukketAV","Ja",
    "EnkeltLeddNum","IkkeSlutt","BForstLukket","Ja",
    "EnkeltLeddNum","IkkeStart","PTTilfredsBesvart","Nei",
    "EnkeltLeddNum","IkkeStart","PTArsakIkkeBesvart","Nei",
    "EnkeltLeddNum","IkkeStart","PT01OnsketInvolv","Nei",
    "EnkeltLeddNum","IkkeStart","PT02BleInvolv","Nei",
    "EnkeltLeddNum","IkkeStart","PT03Utfallsvurd","Nei",
    "EnkeltLeddNum","IkkeStart","PT04KontaktBrukerorg","Nei",
    "EnkeltLeddNum","IkkeStart","PT05OrientertBrukerorg","Nei",
    "EnkeltLeddNum","IkkeStart","PTLukketViaEproms","Nei",
    "EnkeltLeddNum","IkkeStart","PTForstLukketAV","Nei",
    "EnkeltLeddNum","IkkeStart","PTForstLukket","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm1KunUtredning","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm1Poliklinikk","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm1Dag","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm1Dogn","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm2Tvang","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm3Ernaring","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm4Avbrudd","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm5Arsak","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm6Utfall","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm7Individuell","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm7Gruppe","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm7Familieterapi","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm7Flerfamilie","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm8ManualIndividual","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm8ManualGruppe","Nei",
    "EnkeltLeddNum","IkkeStart","BehSpm8ManualFamilieterapi","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm8ManualFlerfamilie","Nei",
    "EnkeltLeddNum","IkkeStart","Beh2Spm9Oppfolging","Nei")


usethis::use_data(resh_voksen_barn, variabeloversikt, overwrite = TRUE)
