SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `AlleScorer`;
CREATE TABLE `AlleScorer` (
  `ForlopsID` int(9) NOT NULL,
  `SDQGlobalScore` tinyint(3) DEFAULT NULL,
  `SDQEmoProb` tinyint(3) DEFAULT NULL,
  `SDQAtferdProb` tinyint(3) DEFAULT NULL,
  `SDQHyperaktivitet` tinyint(3) DEFAULT NULL,
  `SDQVennerProb` tinyint(3) DEFAULT NULL,
  `SDQSosialProb` tinyint(3) DEFAULT NULL,
  `SDQEksternScore` tinyint(3) DEFAULT NULL,
  `SDQInternScore` tinyint(3) DEFAULT NULL,
  `SDQImpactScore` tinyint(3) DEFAULT NULL,
  `SDQPGlobalScore` tinyint(3) DEFAULT NULL,
  `SDQPEmoProb` tinyint(3) DEFAULT NULL,
  `SDQPAtferdProb` tinyint(3) DEFAULT NULL,
  `SDQPHyperaktivitet` tinyint(3) DEFAULT NULL,
  `SDQPVennerProb` tinyint(3) DEFAULT NULL,
  `SDQPSosialProb` tinyint(3) DEFAULT NULL,
  `SDQPEksternScore` tinyint(3) DEFAULT NULL,
  `SDQPInternScore` tinyint(3) DEFAULT NULL,
  `SDQPImpactScore` tinyint(3) DEFAULT NULL,
  `SCL90Somatisering` decimal(6,2) DEFAULT NULL,
  `SCL90Tvang` decimal(6,2) DEFAULT NULL,
  `SCL90Sensitivitet` decimal(6,2) DEFAULT NULL,
  `SCL90Depresjon` decimal(6,2) DEFAULT NULL,
  `SCL90Angst` decimal(6,2) DEFAULT NULL,
  `SCL90Fiendlighet` decimal(6,2) DEFAULT NULL,
  `SCL90Fobi` decimal(6,2) DEFAULT NULL,
  `SCL90Paranoia` decimal(6,2) DEFAULT NULL,
  `SCL90Psykotisk` decimal(6,2) DEFAULT NULL,
  `SCL90Tillegg` tinyint(3) DEFAULT NULL,
  `SCL90GSI` decimal(6,2) DEFAULT NULL,
  `SCL90PST` tinyint(3) DEFAULT NULL,
  `SCL90PSDI` decimal(6,2) DEFAULT NULL,
  `SCL90TSomatisering` tinyint(3) DEFAULT NULL,
  `SCL90TTvang` tinyint(3) DEFAULT NULL,
  `SCL90TSensitivitet` tinyint(3) DEFAULT NULL,
  `SCL90TDepresjon` tinyint(3) DEFAULT NULL,
  `SCL90TAngst` tinyint(3) DEFAULT NULL,
  `SCL90TFiendlighet` tinyint(3) DEFAULT NULL,
  `SCL90TFobi` tinyint(3) DEFAULT NULL,
  `SCL90TParanoia` tinyint(3) DEFAULT NULL,
  `SCL90TPsykotisk` tinyint(3) DEFAULT NULL,
  `SCL90TGSI` tinyint(3) DEFAULT NULL,
  `SCL90TPST` tinyint(3) DEFAULT NULL,
  `SCL90TPSDI` tinyint(3) DEFAULT NULL,
  `SCL90ZSomatisering` decimal(3,1) DEFAULT NULL,
  `SCL90ZTvang` decimal(3,1) DEFAULT NULL,
  `SCL90ZSensitivitet` decimal(3,1) DEFAULT NULL,
  `SCL90ZDepresjon` decimal(3,1) DEFAULT NULL,
  `SCL90ZAngst` decimal(3,1) DEFAULT NULL,
  `SCL90ZFiendlighet` decimal(3,1) DEFAULT NULL,
  `SCL90ZFobi` decimal(3,1) DEFAULT NULL,
  `SCL90ZParanoia` decimal(3,1) DEFAULT NULL,
  `SCL90ZPsykotisk` decimal(3,1) DEFAULT NULL,
  `SCL90ZGSI` decimal(3,1) DEFAULT NULL,
  `SCL90ZPST` decimal(3,1) DEFAULT NULL,
  `SCL90ZPSDI` decimal(3,1) DEFAULT NULL,
  `SCL90PSomatisering` tinyint(3) DEFAULT NULL,
  `SCL90PTvang` tinyint(3) DEFAULT NULL,
  `SCL90PSensitivitet` tinyint(3) DEFAULT NULL,
  `SCL90PDepresjon` tinyint(3) DEFAULT NULL,
  `SCL90PAngst` tinyint(3) DEFAULT NULL,
  `SCL90PFiendlighet` tinyint(3) DEFAULT NULL,
  `SCL90PFobi` tinyint(3) DEFAULT NULL,
  `SCL90PParanoia` tinyint(3) DEFAULT NULL,
  `SCL90PPsykotisk` tinyint(3) DEFAULT NULL,
  `SCL90PGSI` tinyint(3) DEFAULT NULL,
  `SCL90PPST` tinyint(3) DEFAULT NULL,
  `SCL90PPSDI` tinyint(3) DEFAULT NULL,
  `RAND36FysFunk` tinyint(3) DEFAULT NULL,
  `RAND36RollebegFys` tinyint(3) DEFAULT NULL,
  `RAND36RollebegEmo` tinyint(3) DEFAULT NULL,
  `RAND36Tretthet` tinyint(3) DEFAULT NULL,
  `RAND36MentalHelse` tinyint(3) DEFAULT NULL,
  `RAND36SosialFunk` tinyint(3) DEFAULT NULL,
  `RAND36Smerte` tinyint(3) DEFAULT NULL,
  `RAND36GenHelse` tinyint(3) DEFAULT NULL,
  `RAND36EndringHelse` tinyint(3) DEFAULT NULL,
  `EDEQ60GlobalScore` decimal(4,2) DEFAULT NULL,
  `EDEQ60Restriksjon` decimal(4,2) DEFAULT NULL,
  `EDEQ60Kroppsform` decimal(4,2) DEFAULT NULL,
  `EDEQ60Spising` decimal(4,2) DEFAULT NULL,
  `EDEQ60Vekt` decimal(4,2) DEFAULT NULL,
  `CIA30GlobalScore` tinyint(3) DEFAULT NULL,
  `CIA30Personlig` tinyint(3) DEFAULT NULL,
  `CIA30Kognitiv` tinyint(3) DEFAULT NULL,
  `CIA30Sosial` tinyint(3) DEFAULT NULL,
  `PasOppErfaring` decimal(5,2) DEFAULT NULL,
  `PasOppTilfredshet` decimal(5,2) DEFAULT NULL,
  `PasOppTilgjengelighet` decimal(5,2) DEFAULT NULL,
  `PasOppSikkerhet` decimal(5,2) DEFAULT NULL,
  `HoNOSSumScore` tinyint(3) DEFAULT NULL,
  `HoNOSSnittScore` decimal(4,2) DEFAULT NULL,
  `HoNOSAntSvar` tinyint(3) DEFAULT NULL,
  `HoNOSCATotalSum` tinyint(3) DEFAULT NULL,
  `HoNOSCATotalSnitt` decimal(4,2) DEFAULT NULL,
  `HoNOSCADelASum` tinyint(3) DEFAULT NULL,
  `HoNOSCADelASnitt` decimal(4,2) DEFAULT NULL,
  `HoNOSCADelBSum` tinyint(3) DEFAULT NULL,
  `HoNOSCADelBSnitt` decimal(4,2) DEFAULT NULL,
  `HoNOSCATotalSvar` tinyint(3) DEFAULT NULL,
  `HoNOSCADelASvar` tinyint(3) DEFAULT NULL,
  `HoNOSCADelBSvar` tinyint(3) DEFAULT NULL,
  `KidScreenFysisk` tinyint(3) DEFAULT NULL,
  `KidScreenFoelelser` tinyint(3) DEFAULT NULL,
  `KidScreenFamilie` tinyint(3) DEFAULT NULL,
  `KidScreenVenner` tinyint(3) DEFAULT NULL,
  `KidScreenSkole` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `Behandling`;
CREATE TABLE `Behandling` (
  `BehandlingID` int(9) NOT NULL,
  `ForlopsID` int(10) unsigned DEFAULT NULL,
  `BehTiltak` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehIndivid` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTilnInd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehManualind` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehGruppe` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTilnGruppe` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehManualGruppe` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehFamilie` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTilnFamilie` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehManualFamilie` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehFlerFamilie` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTilnFlerFamilie` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehManualFlerFamilie` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehUtfallsvurdTiltak` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehStartTiltak` date DEFAULT NULL,
  `BehSluttTiltak` date DEFAULT NULL,
  PRIMARY KEY (`BehandlingID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `BehandlingNum`;
CREATE TABLE `BehandlingNum` (
  `BehandlingID` int(9) NOT NULL,
  `ForlopsID` int(10) unsigned DEFAULT NULL,
  `BehTiltak` int(10) unsigned DEFAULT NULL,
  `BehIndivid` tinyint(3) DEFAULT NULL,
  `BehTilnInd` tinyint(3) DEFAULT NULL,
  `BehManualind` tinyint(3) DEFAULT NULL,
  `BehGruppe` tinyint(3) DEFAULT NULL,
  `BehTilnGruppe` tinyint(3) DEFAULT NULL,
  `BehManualGruppe` tinyint(3) DEFAULT NULL,
  `BehFamilie` tinyint(3) DEFAULT NULL,
  `BehTilnFamilie` tinyint(3) DEFAULT NULL,
  `BehManualFamilie` tinyint(3) DEFAULT NULL,
  `BehFlerFamilie` tinyint(3) DEFAULT NULL,
  `BehTilnFlerFamilie` tinyint(3) DEFAULT NULL,
  `BehManualFlerFamilie` tinyint(3) DEFAULT NULL,
  `BehUtfallsvurdTiltak` tinyint(3) DEFAULT NULL,
  `BehStartTiltak` date DEFAULT NULL,
  `BehSluttTiltak` date DEFAULT NULL,
  PRIMARY KEY (`BehandlingID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `Brukerliste`;
CREATE TABLE `Brukerliste` (
  `BrukerID` varchar(30) COLLATE utf8_danish_ci NOT NULL,
  `Fornavn` varchar(40) COLLATE utf8_danish_ci DEFAULT NULL,
  `Etternavn` varchar(40) COLLATE utf8_danish_ci DEFAULT NULL,
  `Tittel` int(11) DEFAULT NULL,
  `OpprettetDato` timestamp NULL DEFAULT NULL,
  `SistInnlogget` timestamp NULL DEFAULT NULL,
  `Tlf1` varchar(20) COLLATE utf8_danish_ci DEFAULT NULL,
  `Tlf2` varchar(20) COLLATE utf8_danish_ci DEFAULT NULL,
  `Epost` varchar(60) COLLATE utf8_danish_ci DEFAULT NULL,
  `Rolle` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `RolleBeskrivelse` varchar(300) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `RESHNavnFullt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusKort` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `Enhetstype` binary(1) DEFAULT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`BrukerID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `EnkeltLedd`;
CREATE TABLE `EnkeltLedd` (
  `PasientID` int(10) unsigned DEFAULT NULL,
  `Fylke` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `DiagBUAkse1` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse2` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse3` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse4` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse5` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse6` smallint(6) DEFAULT NULL,
  `DiagBUDSM5utfylles` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUDSM5Hoved` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUDSM5ANSub` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUDSM5AnnenSub` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUDSM5ANAlvGrd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUDSM5BNAlvGrd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUDSM5OverspisAlvGrd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUForstLukket` timestamp NULL DEFAULT NULL,
  `DiagVSF` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVSomatiske` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVMalabsorpsjon` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVDiabetes` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVDSM5utfylles` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVDSM5Hoved` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVDSM5ANSub` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVDSM5AnnenSub` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVDSM5ANAlvGrd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVDSM5BNAlvGrd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVDSM5OverspisAlvGrd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVForstLukket` timestamp NULL DEFAULT NULL,
  `EDETilfredsBesvart` tinyint(3) DEFAULT NULL,
  `EDEArsakIkkeBesvart` tinyint(3) DEFAULT NULL,
  `EDE13GgrOverspis` smallint(6) DEFAULT NULL,
  `EDE14Kontrolltap` smallint(6) DEFAULT NULL,
  `EDE15DgrOverspis` tinyint(3) DEFAULT NULL,
  `EDE16GgrOppkast` smallint(6) DEFAULT NULL,
  `EDE17GgrLaxantia` smallint(6) DEFAULT NULL,
  `EDE18GgrTrening` smallint(6) DEFAULT NULL,
  `EDEVektSelvrapportert` decimal(4,1) DEFAULT NULL,
  `EDEVektSelvrapportertMangler` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `EDEHoydeSelvrapportert` smallint(6) DEFAULT NULL,
  `EDEHoydeSelvrapportertMangler` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `EDEBMISelvrapportert` decimal(5,1) DEFAULT NULL,
  `EDEBMIKatSelvrapportert` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `EDELukketViaEproms` tinyint(3) DEFAULT NULL,
  `EDEForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `EDEForstLukket` timestamp NULL DEFAULT NULL,
  `H01Atferd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H02Selvskade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H03Rusmisbruk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H04KognitiveProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H05FysiskeProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H06Hallusinasjoner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H07Stemningsleie` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H08AndreProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H08aVelgTypeProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H09ForhAndre` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H10ADLProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H11BoligProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `H12YrkeProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `HForstLukket` timestamp NULL DEFAULT NULL,
  `HCA01Atferd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA02Aktivitetsniva` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA03Selvskade` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA04Rusmisbruk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA05SkoleSprak` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA06FysiskProblem` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA07Hallusinasjoner` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA08SomatiskSymp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA09EmosjonelleSymp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA10JevnaldrProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA11Egenomsorg` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA12FamilieProbl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCASkoleframmote` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCADelButfylles` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA14ProblKunnskap` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCA15Mangelinfo` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCAForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCAForstLukket` timestamp NULL DEFAULT NULL,
  `BehUkomplettSkjema` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehDatoStartBeh` date DEFAULT NULL,
  `BehDatoSluttAvbrudd` date DEFAULT NULL,
  `BehUtfallsvurdSamlet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehVidereBeh` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehFastlege` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehOvrigPrimarhtj` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehSpeshtj` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehPrivatSpes` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehAnInstans` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehAvbruddsgrunn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehAvbruddsgrunnSps` varchar(120) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehOppfolging` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehDodUnderBeh` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvang` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvObsMDogn` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvObsUDogn` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvPHMDogn` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvMDognLegemidler` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvMDognErnaring` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvPHUDogn` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvUDognLegemidler` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehTvUDognErnaring` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehRegTiltak` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehGjennomforing` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehForstLukket` timestamp NULL DEFAULT NULL,
  `RegHendelsesdato` date DEFAULT NULL,
  `RegRegtype` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RegHenvMottattDato` date DEFAULT NULL,
  `RegHenvInstans` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RegOpftype` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RegTilhorendeStartReg` varchar(17) COLLATE utf8_danish_ci DEFAULT NULL,
  `RegPasientbesvarelser` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedUkomplettSkjema` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedVekt` decimal(4,1) DEFAULT NULL,
  `MedHoyde` decimal(3,2) DEFAULT NULL,
  `MedBMI` decimal(5,1) DEFAULT NULL,
  `MedBMIkategori` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedBMIpersentilBGS` decimal(4,1) DEFAULT NULL,
  `MedBMIpersentilCDC` decimal(4,1) DEFAULT NULL,
  `MedIsoBMIBGS` decimal(4,1) DEFAULT NULL,
  `MedIsoBMICDC` decimal(4,1) DEFAULT NULL,
  `MedBlodprove` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedBeintetthMaling` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedBeintetthRes` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedPsykofarmaka` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedAntidepressiva` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedBenzodiazepiner` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedNevroleptika` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedAnnenMedBeh` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedForstLukket` timestamp NULL DEFAULT NULL,
  `POTilfredsBesvart` tinyint(3) DEFAULT NULL,
  `POArsakIkkeBesvart` tinyint(3) DEFAULT NULL,
  `PO01Forstod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO02Tillit` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO03InfoDiagnose` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO04Tilpasset` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO05Involvert` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO06Organisert` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO07Tilfredsstillende` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO08Tilgjengelighet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO09Utbytte` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PO10Pasientsikkerhet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `POLukketViaEproms` tinyint(3) DEFAULT NULL,
  `POForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `POForstLukket` timestamp NULL DEFAULT NULL,
  `BTilfredsBesvart` tinyint(3) DEFAULT NULL,
  `BArsakIkkeBesvart` tinyint(3) DEFAULT NULL,
  `B01Sivilstatus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B02EgneBarn` tinyint(3) DEFAULT NULL,
  `B03Bosituasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B04PabegyntUtd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B05FullfortUtd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B06Hovedaktivitet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B07Hovedinntekt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B08StartAldrProbl` smallint(6) DEFAULT NULL,
  `B09LavestVekt` smallint(6) DEFAULT NULL,
  `B09aAldrLavestVekt` smallint(6) DEFAULT NULL,
  `B10HoyestVekt` smallint(6) DEFAULT NULL,
  `B10aAldrHoyestVekt` smallint(6) DEFAULT NULL,
  `B11FamilieSF` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B12TidlBehSF` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B12aPrimarhtj` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `B12aSpesialisthtj` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `B12aSpesEnhetSF` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `B12aAnnenInstans` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `B12bTidlTvangsinnl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B12cAldrForsteBeh` smallint(6) DEFAULT NULL,
  `B12dArTilBehstart` smallint(6) DEFAULT NULL,
  `B12dMndTilBehstart` tinyint(3) DEFAULT NULL,
  `B13MensNoenGang` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B14MensSiste3mnd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B15MedPrevensjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B16Gravid` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B17FysMishandl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B18PsykMishandl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B19Overgrep` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B20Mobbing` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B21SelvskadTidl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B22SelvskadSisteAr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B23SelvmordFTidl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B24SelvmordFSisteAr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `B25Avhengighet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BLukketViaEproms` tinyint(3) DEFAULT NULL,
  `BForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `BForstLukket` timestamp NULL DEFAULT NULL,
  `PTTilfredsBesvart` tinyint(3) DEFAULT NULL,
  `PTArsakIkkeBesvart` tinyint(3) DEFAULT NULL,
  `PT01OnsketInvolv` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PT02BleInvolv` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PT03Utfallsvurd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PT04KontaktBrukerorg` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PT05OrientertBrukerorg` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PTLukketViaEproms` tinyint(3) DEFAULT NULL,
  `PTForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `PTForstLukket` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `EnkeltLeddNum`;
CREATE TABLE `EnkeltLeddNum` (
  `PasientID` int(10) unsigned DEFAULT NULL,
  `Fylke` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `DiagBUAkse1` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse2` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse3` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse4` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse5` varchar(341) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUAkse6` smallint(6) DEFAULT NULL,
  `DiagBUDSM5utfylles` tinyint(3) DEFAULT NULL,
  `DiagBUDSM5Hoved` tinyint(3) DEFAULT NULL,
  `DiagBUDSM5ANSub` tinyint(3) DEFAULT NULL,
  `DiagBUDSM5AnnenSub` tinyint(3) DEFAULT NULL,
  `DiagBUDSM5ANAlvGrd` tinyint(3) DEFAULT NULL,
  `DiagBUDSM5BNAlvGrd` tinyint(3) DEFAULT NULL,
  `DiagBUDSM5OverspisAlvGrd` tinyint(3) DEFAULT NULL,
  `DiagBUForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagBUForstLukket` timestamp NULL DEFAULT NULL,
  `DiagVSF` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVSomatiske` tinyint(3) DEFAULT NULL,
  `DiagVMalabsorpsjon` tinyint(3) DEFAULT NULL,
  `DiagVDiabetes` tinyint(3) DEFAULT NULL,
  `DiagVDSM5utfylles` tinyint(3) DEFAULT NULL,
  `DiagVDSM5Hoved` tinyint(3) DEFAULT NULL,
  `DiagVDSM5ANSub` tinyint(3) DEFAULT NULL,
  `DiagVDSM5AnnenSub` tinyint(3) DEFAULT NULL,
  `DiagVDSM5ANAlvGrd` tinyint(3) DEFAULT NULL,
  `DiagVDSM5BNAlvGrd` tinyint(3) DEFAULT NULL,
  `DiagVDSM5OverspisAlvGrd` tinyint(3) DEFAULT NULL,
  `DiagVForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagVForstLukket` timestamp NULL DEFAULT NULL,
  `EDETilfredsBesvart` tinyint(3) DEFAULT NULL,
  `EDEArsakIkkeBesvart` tinyint(3) DEFAULT NULL,
  `EDE13GgrOverspis` smallint(6) DEFAULT NULL,
  `EDE14Kontrolltap` smallint(6) DEFAULT NULL,
  `EDE15DgrOverspis` tinyint(3) DEFAULT NULL,
  `EDE16GgrOppkast` smallint(6) DEFAULT NULL,
  `EDE17GgrLaxantia` smallint(6) DEFAULT NULL,
  `EDE18GgrTrening` smallint(6) DEFAULT NULL,
  `EDEVektSelvrapportert` decimal(4,1) DEFAULT NULL,
  `EDEVektSelvrapportertMangler` tinyint(3) DEFAULT NULL,
  `EDEHoydeSelvrapportert` smallint(6) DEFAULT NULL,
  `EDEHoydeSelvrapportertMangler` tinyint(3) DEFAULT NULL,
  `EDEBMISelvrapportert` decimal(5,1) DEFAULT NULL,
  `EDEBMIKatSelvrapportert` int(11) DEFAULT NULL,
  `EDELukketViaEproms` tinyint(3) DEFAULT NULL,
  `EDEForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `EDEForstLukket` timestamp NULL DEFAULT NULL,
  `H01Atferd` tinyint(3) DEFAULT NULL,
  `H02Selvskade` tinyint(3) DEFAULT NULL,
  `H03Rusmisbruk` tinyint(3) DEFAULT NULL,
  `H04KognitiveProbl` tinyint(3) DEFAULT NULL,
  `H05FysiskeProbl` tinyint(3) DEFAULT NULL,
  `H06Hallusinasjoner` tinyint(3) DEFAULT NULL,
  `H07Stemningsleie` tinyint(3) DEFAULT NULL,
  `H08AndreProbl` tinyint(3) DEFAULT NULL,
  `H08aVelgTypeProbl` tinyint(3) DEFAULT NULL,
  `H09ForhAndre` tinyint(3) DEFAULT NULL,
  `H10ADLProbl` tinyint(3) DEFAULT NULL,
  `H11BoligProbl` tinyint(3) DEFAULT NULL,
  `H12YrkeProbl` tinyint(3) DEFAULT NULL,
  `HForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `HForstLukket` timestamp NULL DEFAULT NULL,
  `HCA01Atferd` tinyint(3) DEFAULT NULL,
  `HCA02Aktivitetsniva` tinyint(3) DEFAULT NULL,
  `HCA03Selvskade` tinyint(3) DEFAULT NULL,
  `HCA04Rusmisbruk` tinyint(3) DEFAULT NULL,
  `HCA05SkoleSprak` tinyint(3) DEFAULT NULL,
  `HCA06FysiskProblem` tinyint(3) DEFAULT NULL,
  `HCA07Hallusinasjoner` tinyint(3) DEFAULT NULL,
  `HCA08SomatiskSymp` tinyint(3) DEFAULT NULL,
  `HCA09EmosjonelleSymp` tinyint(3) DEFAULT NULL,
  `HCA10JevnaldrProbl` tinyint(3) DEFAULT NULL,
  `HCA11Egenomsorg` tinyint(3) DEFAULT NULL,
  `HCA12FamilieProbl` tinyint(3) DEFAULT NULL,
  `HCASkoleframmote` tinyint(3) DEFAULT NULL,
  `HCADelButfylles` tinyint(3) DEFAULT NULL,
  `HCA14ProblKunnskap` tinyint(3) DEFAULT NULL,
  `HCA15Mangelinfo` tinyint(3) DEFAULT NULL,
  `HCAForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `HCAForstLukket` timestamp NULL DEFAULT NULL,
  `BehUkomplettSkjema` tinyint(3) DEFAULT NULL,
  `BehDatoStartBeh` date DEFAULT NULL,
  `BehDatoSluttAvbrudd` date DEFAULT NULL,
  `BehUtfallsvurdSamlet` tinyint(3) DEFAULT NULL,
  `BehVidereBeh` tinyint(3) DEFAULT NULL,
  `BehFastlege` tinyint(3) DEFAULT NULL,
  `BehOvrigPrimarhtj` tinyint(3) DEFAULT NULL,
  `BehSpeshtj` tinyint(3) DEFAULT NULL,
  `BehPrivatSpes` tinyint(3) DEFAULT NULL,
  `BehAnInstans` tinyint(3) DEFAULT NULL,
  `BehAvbruddsgrunn` tinyint(3) DEFAULT NULL,
  `BehAvbruddsgrunnSps` varchar(120) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehOppfolging` tinyint(3) DEFAULT NULL,
  `BehDodUnderBeh` tinyint(3) DEFAULT NULL,
  `BehTvang` tinyint(3) DEFAULT NULL,
  `BehTvObsMDogn` tinyint(3) DEFAULT NULL,
  `BehTvObsUDogn` tinyint(3) DEFAULT NULL,
  `BehTvPHMDogn` tinyint(3) DEFAULT NULL,
  `BehTvMDognLegemidler` tinyint(3) DEFAULT NULL,
  `BehTvMDognErnaring` tinyint(3) DEFAULT NULL,
  `BehTvPHUDogn` tinyint(3) DEFAULT NULL,
  `BehTvUDognLegemidler` tinyint(3) DEFAULT NULL,
  `BehTvUDognErnaring` tinyint(3) DEFAULT NULL,
  `BehRegTiltak` tinyint(3) DEFAULT NULL,
  `BehGjennomforing` tinyint(3) DEFAULT NULL,
  `BehForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehForstLukket` timestamp NULL DEFAULT NULL,
  `RegHendelsesdato` date DEFAULT NULL,
  `RegRegtype` tinyint(3) DEFAULT NULL,
  `RegHenvMottattDato` date DEFAULT NULL,
  `RegHenvInstans` tinyint(3) DEFAULT NULL,
  `RegOpftype` tinyint(3) DEFAULT NULL,
  `RegTilhorendeStartReg` int(10) unsigned DEFAULT NULL,
  `RegPasientbesvarelser` tinyint(3) DEFAULT NULL,
  `MedUkomplettSkjema` tinyint(3) DEFAULT NULL,
  `MedVekt` decimal(4,1) DEFAULT NULL,
  `MedHoyde` decimal(3,2) DEFAULT NULL,
  `MedBMI` decimal(5,1) DEFAULT NULL,
  `MedBMIkategori` int(11) DEFAULT NULL,
  `MedBMIpersentilBGS` decimal(4,1) DEFAULT NULL,
  `MedBMIpersentilCDC` decimal(4,1) DEFAULT NULL,
  `MedIsoBMIBGS` decimal(4,1) DEFAULT NULL,
  `MedIsoBMICDC` decimal(4,1) DEFAULT NULL,
  `MedBlodprove` tinyint(3) DEFAULT NULL,
  `MedBeintetthMaling` tinyint(3) DEFAULT NULL,
  `MedBeintetthRes` tinyint(3) DEFAULT NULL,
  `MedPsykofarmaka` tinyint(3) DEFAULT NULL,
  `MedAntidepressiva` tinyint(3) DEFAULT NULL,
  `MedBenzodiazepiner` tinyint(3) DEFAULT NULL,
  `MedNevroleptika` tinyint(3) DEFAULT NULL,
  `MedAnnenMedBeh` tinyint(3) DEFAULT NULL,
  `MedForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `MedForstLukket` timestamp NULL DEFAULT NULL,
  `POTilfredsBesvart` tinyint(3) DEFAULT NULL,
  `POArsakIkkeBesvart` tinyint(3) DEFAULT NULL,
  `PO01Forstod` tinyint(3) DEFAULT NULL,
  `PO02Tillit` tinyint(3) DEFAULT NULL,
  `PO03InfoDiagnose` tinyint(3) DEFAULT NULL,
  `PO04Tilpasset` tinyint(3) DEFAULT NULL,
  `PO05Involvert` tinyint(3) DEFAULT NULL,
  `PO06Organisert` tinyint(3) DEFAULT NULL,
  `PO07Tilfredsstillende` tinyint(3) DEFAULT NULL,
  `PO08Tilgjengelighet` tinyint(3) DEFAULT NULL,
  `PO09Utbytte` tinyint(3) DEFAULT NULL,
  `PO10Pasientsikkerhet` tinyint(3) DEFAULT NULL,
  `POLukketViaEproms` tinyint(3) DEFAULT NULL,
  `POForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `POForstLukket` timestamp NULL DEFAULT NULL,
  `BTilfredsBesvart` tinyint(3) DEFAULT NULL,
  `BArsakIkkeBesvart` tinyint(3) DEFAULT NULL,
  `B01Sivilstatus` tinyint(3) DEFAULT NULL,
  `B02EgneBarn` tinyint(3) DEFAULT NULL,
  `B03Bosituasjon` tinyint(3) DEFAULT NULL,
  `B04PabegyntUtd` tinyint(3) DEFAULT NULL,
  `B05FullfortUtd` tinyint(3) DEFAULT NULL,
  `B06Hovedaktivitet` tinyint(3) DEFAULT NULL,
  `B07Hovedinntekt` tinyint(3) DEFAULT NULL,
  `B08StartAldrProbl` smallint(6) DEFAULT NULL,
  `B09LavestVekt` smallint(6) DEFAULT NULL,
  `B09aAldrLavestVekt` smallint(6) DEFAULT NULL,
  `B10HoyestVekt` smallint(6) DEFAULT NULL,
  `B10aAldrHoyestVekt` smallint(6) DEFAULT NULL,
  `B11FamilieSF` tinyint(3) DEFAULT NULL,
  `B12TidlBehSF` tinyint(3) DEFAULT NULL,
  `B12aPrimarhtj` tinyint(3) DEFAULT NULL,
  `B12aSpesialisthtj` tinyint(3) DEFAULT NULL,
  `B12aSpesEnhetSF` tinyint(3) DEFAULT NULL,
  `B12aAnnenInstans` tinyint(3) DEFAULT NULL,
  `B12bTidlTvangsinnl` tinyint(3) DEFAULT NULL,
  `B12cAldrForsteBeh` smallint(6) DEFAULT NULL,
  `B12dArTilBehstart` smallint(6) DEFAULT NULL,
  `B12dMndTilBehstart` tinyint(3) DEFAULT NULL,
  `B13MensNoenGang` tinyint(3) DEFAULT NULL,
  `B14MensSiste3mnd` tinyint(3) DEFAULT NULL,
  `B15MedPrevensjon` tinyint(3) DEFAULT NULL,
  `B16Gravid` tinyint(3) DEFAULT NULL,
  `B17FysMishandl` tinyint(3) DEFAULT NULL,
  `B18PsykMishandl` tinyint(3) DEFAULT NULL,
  `B19Overgrep` tinyint(3) DEFAULT NULL,
  `B20Mobbing` tinyint(3) DEFAULT NULL,
  `B21SelvskadTidl` tinyint(3) DEFAULT NULL,
  `B22SelvskadSisteAr` tinyint(3) DEFAULT NULL,
  `B23SelvmordFTidl` tinyint(3) DEFAULT NULL,
  `B24SelvmordFSisteAr` tinyint(3) DEFAULT NULL,
  `B25Avhengighet` tinyint(3) DEFAULT NULL,
  `BLukketViaEproms` tinyint(3) DEFAULT NULL,
  `BForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `BForstLukket` timestamp NULL DEFAULT NULL,
  `PTTilfredsBesvart` tinyint(3) DEFAULT NULL,
  `PTArsakIkkeBesvart` tinyint(3) DEFAULT NULL,
  `PT01OnsketInvolv` tinyint(3) DEFAULT NULL,
  `PT02BleInvolv` tinyint(3) DEFAULT NULL,
  `PT03Utfallsvurd` tinyint(3) DEFAULT NULL,
  `PT04KontaktBrukerorg` tinyint(3) DEFAULT NULL,
  `PT05OrientertBrukerorg` tinyint(3) DEFAULT NULL,
  `PTLukketViaEproms` tinyint(3) DEFAULT NULL,
  `PTForstLukketAV` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `PTForstLukket` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `ForlopsOversikt`;
CREATE TABLE `ForlopsOversikt` (
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientID` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostNr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostSted` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kommune` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `KommuneNr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fylke` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `FylkeNr` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `KryptertFnr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientKjonn` varchar(13) COLLATE utf8_danish_ci DEFAULT NULL,
  `erMann` varchar(1) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientAlder` decimal(12,4) DEFAULT NULL,
  `Fodselsdato` date DEFAULT NULL,
  `Norsktalende` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sivilstatus` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtdanningSSB` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Avdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdodDato` date DEFAULT NULL,
  `ForlopsID` varchar(10) COLLATE utf8_danish_ci NOT NULL,
  `BasisRegStatus` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType1` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType1Num` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType2` varchar(25) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType2Num` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `KobletForlopsID` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `HovedDato` date DEFAULT NULL,
  `OppflgRegStatus` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  `ErOppflg` int(11) DEFAULT NULL,
  `OppflgStatus` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppflgSekNr` binary(1) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_ForlopsOversikt` (`AvdRESH`,`HovedDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `SkjemaOversikt`;
CREATE TABLE `SkjemaOversikt` (
  `Skjemanavn` varchar(20) COLLATE utf8_danish_ci NOT NULL,
  `SkjemaStatus` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` varchar(10) COLLATE utf8_danish_ci NOT NULL,
  `OpprettetAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `OpprettetDato` timestamp NULL DEFAULT NULL,
  `SistLagretAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SistLagretDato` timestamp NULL DEFAULT NULL,
  `HovedDato` date DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaRekkeflg` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`,`Skjemanavn`),
  KEY `idx_SkjemaOversikt` (`AvdRESH`,`HovedDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;
