---
title: "Veiledning for bruk av Rapporteket for NorSpis"
author: "NorSpis"
date: '`r format(Sys.time(), "%d. %B %Y")`'
---

## Velkommen til NorSpis på Rapporteket

### Navigering
Bruk fanene i toppen til å navigere til ulike typer rapporter.

### Retningslinjer for bruk: hvem, hva, hvor?
Formålet med Rapporteket er å gi sykehusavdelingene statistikk og resultater som kan benyttes i det kontinuerlige forbedringsarbeidet. Rapportene er ment for intern bruk ved de registrerende behandlingsenhetene.

Rapportene inneholder anonymiserte data. I tilfeller der man foretar utvalg som gir rapporter med få pasienter og hvor man kombinerer flere ulike utvalg og rapporter kan det ikke utelukkes med absolutt sikkerhet at rapporter kan
tilbakeføres til enkeltpersoner.

Husk:

* Bruk rapportene internt

* Avklar ekstern bruk med NorSpis (for eksempel ved ønske om bruk overfor media)

### Tolkning
Det er den enkelte avdeling som best forstår sine resultater. Samtidig anmoder vi om at rapportene i Rapporteket brukes kritisk. Utvis forsiktighet ved tolking. Ufullstendige datasett gjør at man må vurdere representativiteten. Med representativitet forstår vi hvor godt resultatene speiler pasientgruppens virkelige tilstand eller resultater. Lav dekningsgrad, samt at ikke alle data er ferdigstilt for aktuell tidsperiode, vil kunne bidra til lav
representativitet når de man ikke har svar fra skiller seg fra de man har svar fra, noe som ofte er tilfellet. På lignende måte vil forløpskompletthet (andel registreringer med levert sluttregistrering) påvirke representativiteten på rapporter som bruker data fra sluttregistreringene. Dette er systematiske feilkilder. I nasjonale medisinske kvalitetsregistre er det et mål at dekningsgraden ved avdelingene og nasjonalt, er minst over 60 prosent, og helst over 80 prosent.

Husk:

* Dekningsgrad, aktualitet og forløpskompletthet ved de enkelte enhetene og nasjonalt, vil kunne påvirke hvor representative dataene er

* Nasjonale tall vil vanskelig kunne være representative for andre enn pasientgruppen ved de enhetene som faktisk har registrert i NorSpis i den aktuelle tidsperioden

### Videre utvikling av Rapportekets innhold
Innholdet vil måtte utvikles til å bli stadig mer relevant for behandlingsenhetene. Førsteutgaven(e) av Rapporteket gir dere som brukere et utgangspunkt, fra hvor dere kan være med å utforme innholdet. Endringsforslag og ønsker eller tips om nye rapporter, kan sendes inn til NorSpis på [norspis@nlsh.no](mailto:norspis@nlsh.no).

### Datakvalitet
Dette er en tidlig utgave av Rapporteket. Ved spørsmål til figurene eller mistanke om at figurene eller datagrunnlaget kan inneholde feil, rapporteres det tilbake til registeret.
